### ISSUE TITLE
Question: Are you going to implement mod support for Akarin 1.14+

### ISSUE THREAD

**Issue by XionioXMine** [Akarin-project/Akarin#106]
It would be nice if you could implement support for mods and plugins, at the moment there is no kernel above 1.12 that would launch the mods.

**Comment by WhyDoWeWonder** [comment]
I'm assuming that you are referring to the [AkarinForge](https://github.com/Akarin-project/AkarinForge) project and by "kernel above 1.12" that there isn't a version that can run forge mods designed for Minecraft > 1.12.2. Our current focus in this project, as that's what most of our users are interested in and forge 1.13 implemented a tremendous amount of changes.

**TLDR**: We will at some point, for now, the main focus is the PaperSpigot fork (this project) so don't expect anything for forge 1.13 or above anytime soon.

**Comment by josephworks** [comment]
@cakoyo issue resolved
plz close
