### ISSUE TITLE
Gadgets Menu incompatible. :D

### ISSUE THREAD

**Issue by TheIntelloBox** [Akarin-project/Akarin#11]
Hey ! :D 

Gadgets Menu is incompatible. :D 
Here is the error: https://pastebin.com/sg8NkMiN ! : D

Thanks for fixing it ! :D 
TheIntelloBox. :D

**Comment by cakoyo** [comment]
The plugin detects server software name, we can do nothing.

**Comment by Dimatert9** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/issues/547

**Comment by cakoyo** [comment]
You can change `modified-server-brand-name` in akarin.yml to `Paper` or `PaperSpigot` or `Spigot` to 'fix' this now.

**Comment by cakoyo** [comment]
But this will break plugin that write for Akarin (I don't think there is any right now)

**Comment by OnlyNoobDied** [comment]
Akarin support will be added in the next update.
