### ISSUE TITLE
RedProtect and Multiverse Plugin Crash

### ISSUE THREAD

**Issue by LeePC** [Akarin-project/Akarin#110]
[2020-03-03-1.log](https://github.com/Akarin-project/Akarin/files/4276375/2020-03-03-1.log)

Fix Please

**Comment by cakoyo** [comment]
This doesn't look like an Akarin issue, please make sure that you are using the latest version of the plugin that supports 1.12.2 and reporting it to the plugin if it still occurring.

**Comment by LeePC** [comment]
Works fine on plain paper

**Comment by josephworks** [comment]
This is an issue with ForgeAkarin, not Akarin!!! Please report it at https://GitHub.com/Akarin-project/AkarinForge .

**Comment by cakoyo** [comment]
@josephworks lol, this is not AkarinForge. Akarin 1.12.2 used Mixin and it's why you see something like Forge, but 1.12.2 is untouched for a while.

**Comment by josephworks** [comment]
No, Line 296. 
`com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand`
pneumaticraft is a mod...

**Comment by cakoyo** [comment]
@josephworks but the naming is spigot naming, not MCP

**Comment by josephworks** [comment]
then why is there a mod?
