### ISSUE TITLE
Convert to patches

### ISSUE THREAD

**Issue by tsao-chi** [Akarin-project/Akarin#117]
改为patch的形式可以避免DMCA/EULA/GPL之类的问题，并且开发流程不会有太大改变，只需要多几个脚本。那些脚本可以从 https://github.com/Spottedleaf/Tuinity 复制
（开发人员好像都是中国人，所以我用中文了）
English version:
Changing to the patch format can avoid problems such as DMCA / EULA / GPL, and the development process will not change much, requiring only a few more scripts. Those scripts can be copied from https://github.com/Spottedleaf/Tuinity

**Comment by josephworks** [comment]
Translation to english:

> Changing to the patch format can avoid problems such as DMCA / EULA / GPL, and the development process will not change much, requiring only a few more scripts. Those scripts can be copied from https://github.com/Spottedleaf/Tuinity

**Comment by cakoyo** [comment]
Patches are more difficult to maintain and manage, though not that hard, while some of our developers just don't like them. The intention to use patch is clearly for copyright issues, but obviously we are just a small project and I don't think they will request DMCA down or something, and we will do these when necessary, but currently, I just don't wanna import new confusions.

**Comment by LegacyGamerHD** [comment]
@cakoyo  plz dont force java 11 like  https://github.com/Spottedleaf/Tuinity

**Comment by tsao-chi** [comment]
@LegacyGamerHD java 11 is not necessary

**Comment by LegacyGamerHD** [comment]
well its forced isnt it

**Comment by LegacyGamerHD** [comment]
https://github.com/Spottedleaf/Tuinity/issues/16

**Comment by tsao-chi** [comment]
@LegacyGamerHD It has nothing to do with the form of the project. concurrentutil is a dependency of Tuinity.

**Comment by tsao-chi** [comment]
@cakoyo Sometimes patches are easier to maintain. Changes are split into multiple files, making it easier to port functionality between projects and/or update to a new MC version.

**Comment by josephworks** [comment]
I think using patches is definitely something to consider.

**Comment by tsao-chi** [comment]
But the commits for this project are a bit messy. To convert this project to patches, one need to clean up the commits with `git rebase`.

**Comment by tsao-chi** [comment]
https://github.com/Akarin-project/Akarin/commit/b8e12697cc1d9155f3406317c3e5934aad0484a7 is not much different from PaperSpigot 1.14.4, one can simply re-create a project.

https://paste.debian.net/1135507/

**Comment by josephworks** [comment]
@tsao-chi can you update the README.md with build instructions?

**Comment by tsao-chi** [comment]
@josephworks  https://github.com/Akarin-project/Akarin/pull/136

**Comment by josephworks** [comment]
Thanks!
