### ISSUE TITLE
Does anybody know why CircleCI builds started failing?

### ISSUE THREAD

**Issue by WhyDoWeWonder** [Akarin-project/Akarin#119]
Since build 521 CircleCI keeps on failing. I've manually built Akarin on 3 different machines running Windows, Arch and Debian respectively all with the default scripts. CircleCI always errors out saying the ./paper directory doesn't exist. Any clue what's wrong guys?

**Comment by josephworks** [comment]
It's probably a simple bug with the build file. Most devs just compile the code and use it. Not many people use CircleCI but it would be nice to use Jenkins in the feature as I have a Jenkins server that I can share.

**Comment by WhyDoWeWonder** [comment]
What's stopping you from setting up Jenkins automation right now?

**Comment by josephworks** [comment]
I need to talk to the other devs and get it set up. I will asap.

**Comment by josephworks** [comment]
@WhyDoWeWonder if you need a build of Akarin, I set up the Jenkins server: http://josephworks.ddns.net:8080/job/Akarin-project/job/Akarin/

**Comment by josephworks** [comment]
Fixed!
