### ISSUE TITLE
How to download 1.12.2 version?

### ISSUE THREAD

**Issue by SyqlexxPI** [Akarin-project/Akarin#124]
Where can i download it?

The artifact is missing from the archive.

**Comment by josephworks** [comment]
http://josephworks.ddns.net:8080/job/Akarin-project/job/Akarin/

**Comment by SyqlexxPI** [comment]
Thanks, but there are only 1.14.4 builds? I'm looking for 1.12.2.

**Comment by josephworks** [comment]
Thanks for bringing this to my attention, I will build 1.12.2 on Jenkins RN

**Comment by josephworks** [comment]
Ohh, no problem! Here's the latest 1.12 build: https://github.com/Akarin-project/Akarin/releases/tag/1.12.2-R0.4.2
