### ISSUE TITLE
GitHub CI vs Jenkins

### ISSUE THREAD

**Issue by josephworks** [Akarin-project/Akarin#140]
GitHub CI - 7min 16sec
Jenkins - 6min 40sec

What does this mean?
We will not be using GitHub CI for long and it will be removed as soon as Jenkins is fully set up.

**Comment by josephworks** [comment]
I would like help creating a Jenkinsfile

**Comment by MerdedSpade** [comment]
GitHub Actions has still faster downloads

**Comment by MerdedSpade** [comment]
And it starts right after commit

**Comment by josephworks** [comment]
Jenkins can start right after a commit, has more features, and it doesn't have a noticeable difference in download speed. Any which way, Jenkins is quicker by 36sec...

**Comment by LegacyGamerHD** [comment]
The Jenkins is really slow

**Comment by josephworks** [comment]
If built quicker then GitHub... So wdym?

**Comment by MerdedSpade** [comment]
Downloads

**Comment by LegacyGamerHD** [comment]
@josephworks  we out of europe or china or japan the downloads are far slower then github actions  then your jenkins because of range thats why sotr had circleci for quicker download do it takes 3 to 8 minutes to download a jar from your jenkins

**Comment by josephworks** [comment]
@LegacyGamerHD I did not consider that. The Jenkins server will be for versioned releases and Untied States. The GitHub CI will be the main way to download the latest build.
