### ISSUE TITLE
Port Parallel world #54 to 1.15.2

### ISSUE THREAD

**Issue by tsao-chi** [Akarin-project/Akarin#152]
https://github.com/Akarin-project/Akarin/pull/54

It would be great to have `parallel world` on 1.15.2.
But I don't understand its mechanism and it's in Mixin format which is not easy to convert to patches directly.

**Comment by cakoyo** [comment]
This patch does not work correctly on and after 1.13 for an unknown reason, I have no idea yet.

**Comment by tsao-chi** [comment]
https://github.com/Akarin-project/Akarin/issues/160
