### ISSUE TITLE
Create Jenkinsfile

### ISSUE THREAD

**Issue by josephworks** [Akarin-project/Akarin#156]
Create a Jenkinsfile for a Multibranch Pipeline using Jenkins' blue ocean.

I've been having difficulty with this, and I'll post more details asap.

**Comment by cakoyo** [comment]
A [CI-SKIP] would be nice.

**Comment by josephworks** [comment]
Yeah, I plan to add that

**Comment by josephworks** [comment]
Paused until I get the required ADMIN:HOOKS perms as Jenkins requires it for pipeline project.

**Comment by josephworks** [comment]
Done!
