### ISSUE TITLE
1.15.2: Re-add PandaWire

### ISSUE THREAD

**Issue by LegacyGamerHD** [Akarin-project/Akarin#161]
https://www.spigotmc.org/resources/pandawire.41991/

**Comment by LegacyGamerHD** [comment]
simliar to #42 the old one

**Comment by tsao-chi** [comment]
> For people who using Paper, Paper already built-in an alternative Redstone algorithm by adding `use-faster-eigencraft-redstone` in paper.yml. Don't waste others' time to read your ignorant complaints here.

**Comment by LegacyGamerHD** [comment]
@tsao-chi  tour wrong also panwire wash in 1.13.2 build it hase always been in there

**Comment by LegacyGamerHD** [comment]
> > For people who using Paper, Paper already built-in an alternative Redstone algorithm by adding `use-faster-eigencraft-redstone` in paper.yml. Don't waste others' time to read your ignorant complaints here.

also it isnt complain and hase always been in akarin reopen it

**Comment by josephworks** [comment]
@LegacyGamerHD It was a quote from another Minecrafter, Tsao-chi probably didn't mean it...

**Comment by LegacyGamerHD** [comment]
> @LegacyGamerHD It was a quote from another Minecrafter, Tsao-chi probably didn't mean it...

okey am tired lol
