### ISSUE TITLE
Server Timeout Crash

### ISSUE THREAD

**Issue by Brad123456789** [Akarin-project/Akarin#162]
So what happened was, no one was in the server, My friend joins the game then 10 seconds later the server crashes saying it has stopped responding.

Akarin has been doing this a lot recently, it keeps kicking all the players for the reason Disconnected or timed out and then the server crashes, it's just random when it happens

This is a recent thing that has started to happen and I have not done anything to the server.
I run my server using these command-line arguments. java -server -Xms4096M -Xmx4096M -Dterminal.jline=false -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=45 -XX:G1HeapRegionSize=32M -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+ParallelRefProcEnabled -DIReallyKnowWhatIAmDoingISwear=true -jar akarin-1.12.2.jar
Netty is set to use 24 threads in the spigot.yml but I don't think this is an issue with Netty considering it's a recent issue that has just started to happen.
The server is a kitpvp server attached to my aegis bungee cord jar but the crashing issue is also happening to the Hub server too

Here is the Relevant console logs that it told me to send you.
KITPVP SERVER LOG: https://pastebin.com/FbULhE28
HUB SERVER LOG: https://pastebin.com/tDMR683m

**Comment by josephworks** [comment]
What Java are you using?

Note for Joseph - Nextresponce:
*Make sure that network is using openjdk*
Please update your server flags according to https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/ : 
`java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch  -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=true -Daikars.new.flags=true -jar paperclip.jar nogui`

**Comment by Brad123456789** [comment]
Java Version 8 Update 191 Build 1.8.0_191-b12 
The OS i am using is windows server 2012 R2 Data Center

**Comment by josephworks** [comment]
Please update your java to https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09.1_openj9-0.20.0/OpenJDK8U-jdk_x64_windows_openj9_8u252b09_openj9-0.20.0.msi and delete all old javas that are installed.

**Comment by Brad123456789** [comment]
I Updated my java to that version and the server seems to be a lot stabler than before I'll let you know what happens later on tommorrow to see whether or not the issue has been fixed or not.

**Comment by josephworks** [comment]
Ok

**Comment by josephworks** [comment]
I will not close the issue yet as there are a few more performance fixes I have for your issue

**Comment by josephworks** [comment]
Inactive, guessing that server is working properly
