### ISSUE TITLE
Make 1.12.2 build

### ISSUE THREAD

**Issue by josephworks** [Akarin-project/Akarin#167]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Paper-Parent dev-SNAPSHOT .......................... SUCCESS [  0.582 s]
[INFO] Paper-API 1.12.2-R0.1-SNAPSHOT ..................... SUCCESS [ 48.096 s]
[INFO] Akarin 1.12.2-R0.4-SNAPSHOT ........................ FAILURE [ 50.525 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:39 min
[INFO] Finished at: 2020-05-13T19:53:00-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project akarin: Could not resolve dependencies for project com.destroystokyo.paper:akarin:jar:1.12.2-R0.4-SNAPSHOT: Could not find artifact com.destroystokyo.paper:paper:jar:1.12.2-R0.1-SNAPSHOT in akarin-repo (https://raw.githubusercontent.com/Akarin-project/akarin-repo/master/repository) -> [Help 1]
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
```

**Comment by josephworks** [comment]
Could someone that worked on 1.12.2 dev update the Akarin-repo and add artifact com.destroystokyo.paper:paper:jar:1.12.2-R0.1-SNAPSHOT in akarin-repo.
Thx!

**Comment by Clercq** [comment]
yes please, 1.12.2 most optimized and popular version in the Minecraft at RU segment.
also, could you please build this one on the latest paper version.

The default paper can host 270 players(18-20tps). I think with the akarin it would be better

**Comment by josephworks** [comment]
I've been working on this (as recently as yesterday), and it appears to me that PaperMC does not really want people to be working on 1.12.2. Also, I have discovered that a reason for this is from paper's recent change to papermc.io and the less use of destroysTokyo domain.

**Comment by Clercq** [comment]
maybe, but at this moment paper1.15.2 is too laggy, as far as I can see, it hosts only 150-180 players with highest tps:/

**Comment by josephworks** [comment]
Yeah, I suppose so.

**Comment by lelik01** [comment]
I am waiting for Akarin 1.12.2 source code to be fixed to compile without problems :)

**Comment by josephworks** [comment]
The source code is just fine @lelik01 , the problem is that maven cant download the paper jar.

**Comment by lelik01** [comment]
> 
> 
> The source code is just fine @lelik01 , the problem is that maven cant download the paper jar.

I changed the Paper directory to the official in the "build file", tried all possible ways to compile 1.12.2 and nothing worked.

**Comment by josephworks** [comment]
Yes, cause it is a papermc issue and not an Akarin issue. Usually, we wouldn't fix something like this, but I'm working on it.

**Comment by Clercq** [comment]
maybe try to create&use a mirror of paper repo

**Comment by OmniTroid** [comment]
Does it make sense to add it as a Git submodule like Tuinity?

**Comment by josephworks** [comment]
Um... that's what we are currently doing.

**Comment by josephworks** [comment]
So, use this instead of the current paper in akarin build system yes it should work but remember to add it to the dependency and also fork paper so you can update the 1.12.2 branch and maybe call the repo paper1.12.2? ok thanks

**Comment by satyrnhub** [comment]
Only issue I see with building 1.12.2 now is that it says "cannot find symbol" for everything. Is there something I'm doing wrong?

**Comment by josephworks** [comment]
> Only issue I see with building 1.12.2 now is that it says "cannot find symbol" for everything. Is there something I'm doing wrong?

Nope! I have to fix that. It might be that it is applying 1.13 changes to 1.12.2 code.

**Comment by josephworks** [comment]
So, last time I tried to fix it, I was using java 11 and paper wouldn't build. I reinstalled java8 and will work on dev soon. Sorry for the delay.

**Comment by satyrnhub** [comment]
No problem!

**Comment by satyrnhub** [comment]
Any progress?

**Comment by satyrnhub** [comment]
Just checked, says `Child module /home/user/Akarin/work/Paper/Paper-API of /home/user/Akarin/work/Paper/pom.xml does not exist`

**Comment by satyrnhub** [comment]
```
  Patches applied cleanly to Paper-API
From /home/user/Akarin/work/Paper/work/Spigot/../CraftBukkit
 + 640785d3...2ba4107c patched    -> origin/patched  (forced update)
 + 640785d3...2ba4107c upstream   -> origin/upstream  (forced update)
Resetting Paper-Server to Spigot-Server...
Your branch and 'origin/master' have diverged,
and have 3950 and 8 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
HEAD is now at 8adedc49a mc-dev Imports
  Applying patches to Paper-Server...
fatal: could not open '/home/user/Akarin/work/Paper/Spigot-Server-Patches/*.patch' for reading: No such file or directory
  Something did not apply cleanly to Paper-Server.
  Please review above details and finish the apply then
  save the changes with rebuildPatches.sh
Failed to apply Paper Patches
Failed to build Paper
Failed to build Akarin
```

**Comment by Mathiiss-sudo** [comment]
No, always the same error. Can't wait for it to be fixed :)

**Comment by josephworks** [comment]
Nope, that's not the only error.

**Comment by josephworks** [comment]
Ill work on fix tomorrow.

**Comment by satyrnhub** [comment]
"/

**Comment by satyrnhub** [comment]
Any update on this?

**Comment by josephworks** [comment]
Still a W.I.P. I am working on it. It is harder than I thought. I even rehosted my nexus repo server...

**Comment by josephworks** [comment]
There is a $20 bounty for whoever fixes this.

**Comment by MrIvanPlays** [comment]
> There is a $20 bounty for whoever fixes this.

BRUH

**Comment by LegacyGamerHD** [comment]
good news i got it working finaly

**Comment by Ytoblo** [comment]
> good news i got it working finaly
Nice cock, awesome job xdd
