### ISSUE TITLE
error

### ISSUE THREAD

**Issue by disqetow** [Akarin-project/Akarin#17]
這次我想用中文說明這個問題:

這個端會導致怪物打一次後就無法再攻擊
也會造成玩家無法攻擊玩家 在某些世界
有一些實體問題 這能調整嗎?

**Comment by cakoyo** [comment]
能具体一点吗？最好有复现的步骤，否则我很难修复

**Comment by disqetow** [comment]
剛開服時可以攻擊怪物 後來打一下怪物後 就無法再攻擊 任何東西都沒辦法造成傷害 怪物也沒有動作 不會攻擊玩家 有時候玩家也沒辦法攻擊玩家

**Comment by cakoyo** [comment]
解决方案1：开启Multiverse(或其他有此功能插件)的keep-spawn-chunks功能
解决方案2：不要开启keep-spawn-chunks，但同时关闭paper.yml中的此功能

**Comment by cakoyo** [comment]
之前的版本关闭服务端自带的keep-spawn-chunks会导致无法启动，最新版本已修复
