### ISSUE TITLE
Incomplete build guide

### ISSUE THREAD

**Issue by FireMasterK** [Akarin-project/Akarin#177]
The build guide in the readme does not specify to run `git submodule update --init`
Without that, the following error would occur: https://paste.ubuntu.com/p/3VgnrzpV8V/

**Comment by josephworks** [comment]
um, its ``git submodule update --init --recursive``

**Comment by FireMasterK** [comment]
Oh, interesting that my build was successful even without `--recursive`

**Comment by josephworks** [comment]
I always use it anyways, as it initializes submodules in submodules.
