### ISSUE TITLE
Akarin 1.16 should be master.

### ISSUE THREAD

**Issue by Robob12345** [Akarin-project/Akarin#180]
With Akarin 1.16 being the latest, I feel as though it should be set to the master branch.

**Comment by josephworks** [comment]
No, I don't think that is the case.
1.15.2 is the latest.
When 1.16 releases its last patch, and we upgrade to that version (eg. 1.16.2) then we will switch the default branch.

**Comment by CrazyNutLz** [comment]
I have been using 1.16.1 for a month.
 It's much more powerful than paper .
The maximum number of players can reach 50, which Paper cannot do.
Hopefully there will be better optimizations for multithreading
Thanks a lot

**Comment by josephworks** [comment]
Why are you telling us this here?

**Comment by CrazyNutLz** [comment]
> Why are you telling us this here?


I just want to say that Akarin is amazing 
Hopefully, there will be more optimizations on 1.16.1
If the reply place is wrong, please let me know

**Comment by josephworks** [comment]
Here, join the discord to stay updated: https://discord.gg/dNvNrf5

**Comment by CrazyNutLz** [comment]
> Here, join the discord to stay updated: https://discord.gg/dNvNrf5

Thanks a lot
