### ISSUE TITLE
reply demo server

### ISSUE THREAD

**Issue by ksfhjsf** [Akarin-project/Akarin#184]
im bulid demo server can you put on demoserver
 this is ip ss1.nide8.com:25595

**Comment by josephworks** [comment]
Do you have a cleaner domain name than ``ss1.nide8.com:25595``?

**Comment by Brad123456789** [comment]
Whoever owns the akarin.app domain for the website can create a sub domain or something or a record for the server so its like demo.akarin.app

**Comment by ksfhjsf** [comment]
play.minecraftpencilworld.top  this is ip

**Comment by josephworks** [comment]
IP not found. Are you sure that that works?

**Comment by josephworks** [comment]
> Whoever owns the akarin.app domain for the website can create a subdomain or something or a record for the server so its like demo.akarin.app

The problem with that is that it isn't our (the developers) server, and we don't have perms. We would also have to rebrand everything.

**Comment by josephworks** [comment]
Right now, the servers in the README are an example of some servers that run Akarin, but if larger servers use Akarin, then their name would be added instead. I am thinking of only keeping 7 servers on the README.

**Comment by ksfhjsf** [comment]
is working

**Comment by ksfhjsf** [comment]
play.minecraftpencilworld.top

**Comment by josephworks** [comment]
C:\Users\Joseph Robinson>ping play.minecraftpencilworld.top
Ping request could not find host play.minecraftpencilworld.top. Please check the name and try again.

**Comment by josephworks** [comment]
C:\Users\Joseph Robinson>ping ss1.nide8.com:25595
Ping request could not find host ss1.nide8.com:25595. Please check the name and try again.

**Comment by josephworks** [comment]
For the time being, I cannot access the server, so I amnt comfortable with displaying it on the readme.

If you manage to get the IP working, just send the new IP here.
