### ISSUE TITLE
AKARIN WRONG VERSION

### ISSUE THREAD

**Issue by Foremast69** [Akarin-project/Akarin#185]
You guys say 1.16.2 when it is 1.16.1 and viceversa

**Comment by josephworks** [comment]
Yes, this should of never happened. Unfortunately, I cannot start dev as I can't build Akarin die to a space in my username. I will get this solved soon. We will be going directly to 1.16.3.

**Comment by josephworks** [comment]
This is fixed cause there isn't any 1.16.1 and 1.16.2 anymore (:
