### ISSUE TITLE
Where can I find the old 1.8 Torch server?

### ISSUE THREAD

**Issue by zoeleu** [Akarin-project/Akarin#194]

**Comment by josephworks** [comment]
https://github.com/TorchSpigot/Torch

**Comment by zoeleu** [comment]
No, that's 1.12. Where can I find the **1.8** Torch? I can't find it anywhere.

**Comment by josephworks** [comment]
I have no clue, but this also isn't the place to ask.

**Comment by josephworks** [comment]
https://github.com/xiaonian233/Torch-legacy

**Comment by zoeleu** [comment]
It is, Torch turned into Akarin, right?

**Comment by zoeleu** [comment]
> https://github.com/xiaonian233/Torch-legacy

Thank you!

**Comment by josephworks** [comment]
But this is for reporting issues with Akarin, not torch.
