### ISSUE TITLE
cant load plugin

### ISSUE THREAD

**Issue by disqetow** [Akarin-project/Akarin#2]
https://pastebin.com/chu04XTV 
Still cant load

**Comment by disqetow** [comment]
plugin: https://dev.bukkit.org/projects/nbteditor
and myitem have same problem

**Comment by disqetow** [comment]
Still cant load :O

**Comment by cakoyo** [comment]
CI doesn't sync with the lastest launchwrapper repo which causes the issues, I tried to update the version number of launchwrapper, this may works

**Comment by disqetow** [comment]
Still not work

**Comment by cakoyo** [comment]
Forget to deploy, the next build should be ok
