### ISSUE TITLE
Cannot run on java16

### ISSUE THREAD

**Issue by Canary233** [Akarin-project/Akarin#200]
Unsupported Java detected (60.0). Only up to Java 15 is supported.

**Comment by josephworks** [comment]
Akarin supports Java 8 and Java 11

You might be able to use java 13, but I haven't tested it.

Akarin not running on Java 16 isn't really an issue.

**Comment by Toffikk** [comment]
add `-DPaper.IgnoreJavaVersion=true` to jvm args

**Comment by Toffikk** [comment]
to be able to always use the latest java version , even EA versions

**Comment by josephworks** [comment]
From what I am seeing, java 60.0 is the class version. I am not sure that that will fix the issue.
This means that that version of Akarin was most likely compiled locally with Java 16.
