### ISSUE TITLE
I build a 1.16.5 akarin jar,It can't be used.

### ISSUE THREAD

**Issue by Kogasa-touhou** [Akarin-project/Akarin#201]
![image](https://user-images.githubusercontent.com/67717065/118355680-d3a47800-b5a3-11eb-8d74-069a0e1491f2.png)
What should i do?

**Comment by josephworks** [comment]
what java version are you using?

**Comment by Kogasa-touhou** [comment]
I tried this
![image](https://user-images.githubusercontent.com/67717065/118479337-7c3d0e00-b743-11eb-9232-28424ab033fb.png)
and this 
![image](https://user-images.githubusercontent.com/67717065/118479440-98d94600-b743-11eb-9923-82280b169880.png)

**Comment by josephworks** [comment]
Are you building with ./Akarin jar ?

**Comment by Kogasa-touhou** [comment]
Yes!I found the jar in target.

**Comment by josephworks** [comment]
Are you using 12 or 24hr clock?

**Comment by Kogasa-touhou** [comment]
24hr clock
Both my taptop(windows) and my centos server.

**Comment by Kogasa-touhou** [comment]
![image](https://user-images.githubusercontent.com/67717065/119277979-31485c80-bc55-11eb-8816-c7555e09ebe9.png)
![image](https://user-images.githubusercontent.com/67717065/119277992-3c9b8800-bc55-11eb-9a7f-ed692200860f.png)
Because I am using Chinese as system language?

**Comment by josephworks** [comment]
I see, could you switch to a 12hr clock while compiling to see if that fixes the issue?

**Comment by Kogasa-touhou** [comment]
I tried WSL on my pc.It works Thanks
