### ISSUE TITLE
Akarin for 1.17

### ISSUE THREAD

**Issue by Minionguyjpro** [Akarin-project/Akarin#205]
Please upgrade Akarin to 1.17

**Comment by WesleyVanNeck** [comment]
This is probably not gone happen anytime soon were to busy with our lives rn

**Comment by Minionguyjpro** [comment]
What?

**Comment by Minionguyjpro** [comment]
I then think its outdated about a few years, because who want to play 1.15 when theres 1.17  with even more features?

**Comment by josephworks** [comment]
No? 1.16.5 Akarin exists. And paper 1.17 isn't considered stable yet.

**Comment by Minionguyjpro** [comment]
Oh ok

Op zo 11 jul. 2021 07:53 schreef Joseph Robinson ***@***.***>:

**Comment by WesleyVanNeck** [comment]
> I then think its outdated about a few years, because who want to play 1.15 when theres 1.17 with even more features?

How respectfully... Again, we are busy with our lives and we're not getting paid, so how do want us to work on it. And yes, 1.16.4 is there.

**Comment by WesleyVanNeck** [comment]
Just slab viaversion on it

**Comment by Minionguyjpro** [comment]
No, thats very different. It dont allows you to use the new items in like 1.17.

**Comment by josephworks** [comment]
Akarin will not support 1.17 until the last release (eg. 1.17.4).
