### ISSUE TITLE
Entity ticking & NPC disappearing

### ISSUE THREAD

**Issue by disqetow** [Akarin-project/Akarin#21]
Paperspigot 最新版本出現了一些npc問題 導致akarin 也有這個問題

請看看這個文章: https://github.com/PaperMC/Paper/issues/1197

NPC會突然消失

**Comment by disqetow** [comment]
照你的意思做了 怪物還是無法攻擊..

**Comment by cakoyo** [comment]
但是他们似乎已经[修复](https://github.com/PaperMC/Paper/commit/17525cd54b1f28d62e0b79d75dfe7d60b335faa4)了，仍然有问题吗？

关于那个问题，开启 multiverse 的主世界的 keep-spawn-chunks (= true) 以及 paper.yml 中的 keep-spawn-loaded，如果不能解决 告诉我

**Comment by cakoyo** [comment]
MultiWorld的配置文件中是否有关于这个的设定，如果有，保持同步

**Comment by disqetow** [comment]
沒有 這個錯誤疑似是react 或是 lagassiet 也可能是neverlag引起了錯誤

**Comment by disqetow** [comment]
請問這個端是能讓所有伺服器內容都使用多線程嗎?

**Comment by cakoyo** [comment]
不是全部内容。

**Comment by cakoyo** [comment]
The feature causes this is configurable now if you cannot resolve this by modifying the config of plugins, just set `core.optimize-chunk-unloading` in `akarin.yml` to `false`.

**Comment by cakoyo** [comment]
关于NPC的问题，最好反馈给Paper
