### ISSUE TITLE
upload-pack: not our ref

### ISSUE THREAD

**Issue by zhenaiwork** [Akarin-project/Akarin#210]
if you :
upload-pack: not our ref
you can:
 git submodule update --remote

如果你出现这个报错：upload-pack: not our ref
你可以执行这个看看： git submodule update --remote

希望可以帮到你。

**Comment by zhenaiwork** [comment]
And when will it be updated to 1.18 
:）

**Comment by xism4** [comment]
> And when will it be updated to 1.18 :）

Use Paper or PurpurMC.
