### ISSUE TITLE
1.12.2 build failure?

### ISSUE THREAD

**Issue by ghost** [Akarin-project/Akarin#213]
Log:

[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-Server\target\paper-1.12.2.jar with C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-Server\target\paper-1.12.2-R0.1-SNAPSHOT-shaded.jar
[INFO] Dependency-reduced POM written at: C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-Server\target\dependency-reduced-pom.xml
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ paper ---
[INFO] Installing C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-Server\target\paper-1.12.2.jar to C:\Users\14868\.m2\repository\com\destroystokyo\paper\paper\1.12.2-R0.1-SNAPSHOT\paper-1.12.2-R0.1-SNAPSHOT.jar
[INFO] Installing C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-Server\target\dependency-reduced-pom.xml to C:\Users\14868\.m2\repository\com\destroystokyo\paper\paper\1.12.2-R0.1-SNAPSHOT\paper-1.12.2-R0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Paper-Parent dev-SNAPSHOT .......................... SUCCESS [  0.172 s]
[INFO] Paper-API 1.12.2-R0.1-SNAPSHOT ..................... SUCCESS [  8.207 s]
[INFO] Paper 1.12.2-R0.1-SNAPSHOT ......................... SUCCESS [01:32 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:41 min
[INFO] Finished at: 2022-03-15T20:02:11+08:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] paperclip-java8                                                    [jar]
[INFO] paperclip-java6                                                    [jar]
[INFO] paperclip-java9                                                    [jar]
[INFO] paperclip-assembly                                                 [jar]
[INFO] Paperclip                                                          [pom]
[INFO]
[INFO] -----------------< com.destroystokyo:paperclip-java8 >------------------
[INFO] Building paperclip-java8 1.1-SNAPSHOT                              [1/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Paperclip 1.1-SNAPSHOT:
[INFO]
[INFO] paperclip-java8 .................................... FAILURE [  0.096 s]
[INFO] paperclip-java6 .................................... SKIPPED
[INFO] paperclip-java9 .................................... SKIPPED
[INFO] paperclip-assembly ................................. SKIPPED
[INFO] Paperclip .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.158 s
[INFO] Finished at: 2022-03-15T20:02:12+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project paperclip-java8: Could not resolve dependencies for project com.destroystokyo:paperclip-java8:jar:1.1-SNAPSHOT: Failed to collect dependencies at org.jbsdiff:jbsdiff:jar:1.0-SNAPSHOT: Failed to read artifact descriptor for org.jbsdiff:jbsdiff:jar:1.0-SNAPSHOT: Could not transfer artifact org.jbsdiff:jbsdiff:pom:1.0-SNAPSHOT from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [clojars (http://clojars.org/repo, default, releases+snapshots)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
cp: cannot stat '/c/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/work/Paperclip/assembly/target/paperclip-1.12.2.jar': No such file or directory

Build success!
Copied final jar to /c/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/paperclip.jar
[Akarin] Ready to build
[Akarin] Touch sources..
[Akarin] Test has been skipped
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Paper-Parent                                                       [pom]
[INFO] Paper-API                                                          [jar]
[INFO] Akarin                                                             [jar]
[INFO]
[INFO] ----------------< com.destroystokyo.paper:paper-parent >----------------
[INFO] Building Paper-Parent dev-SNAPSHOT                                 [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ paper-parent ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ paper-parent ---
[INFO] Installing C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\pom.xml to C:\Users\14868\.m2\repository\com\destroystokyo\paper\paper-parent\dev-SNAPSHOT\paper-parent-dev-SNAPSHOT.pom
[INFO]
[INFO] -----------------< com.destroystokyo.paper:paper-api >------------------
[INFO] Building Paper-API 1.12.2-R0.1-SNAPSHOT                            [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ paper-api ---
[INFO] Deleting C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-API\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ paper-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-API\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ paper-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 807 source files to C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-API\target\classes
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/com/destroystokyo/paper/utils/UnsafeUtils.java:[3,16] sun.misc.Unsafe▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/org/spigotmc/CustomTimingsHandler.java:[33,19] sun.reflect.Reflection▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/com/destroystokyo/paper/utils/UnsafeUtils.java:[3,16] sun.misc.Unsafe▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/org/spigotmc/CustomTimingsHandler.java:[33,19] sun.reflect.Reflection▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/com/destroystokyo/paper/utils/UnsafeUtils.java:[3,16] sun.misc.Unsafe▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/org/spigotmc/CustomTimingsHandler.java:[33,19] sun.reflect.Reflection▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/com/destroystokyo/paper/utils/UnsafeUtils.java:[10,26] sun.misc.Unsafe▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/com/destroystokyo/paper/utils/UnsafeUtils.java:[12,9] sun.misc.Unsafe▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/com/destroystokyo/paper/utils/UnsafeUtils.java:[17,23] sun.misc.Unsafe▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/com/destroystokyo/paper/utils/UnsafeUtils.java:[30,19] sun.misc.Unsafe▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[WARNING] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/org/spigotmc/CustomTimingsHandler.java:[55,61] sun.reflect.Reflection▒▒▒ڲ▒ר▒▒ API, ▒▒▒ܻ▒▒▒δ▒▒▒▒▒а▒▒▒ɾ▒▒
[INFO] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/org/bukkit/entity/Player.java: ĳЩ▒▒▒▒▒ļ▒ʹ▒û򸲸▒▒▒▒ѹ▒ʱ▒▒ API▒▒
[INFO] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/org/bukkit/entity/Player.java: ▒й▒▒▒ϸ▒▒Ϣ, ▒▒ʹ▒▒ -Xlint:deprecation ▒▒▒±▒▒롣
[INFO] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/org/bukkit/World.java: ĳЩ▒▒▒▒▒ļ▒ʹ▒▒▒▒δ▒▒▒▒▒򲻰▒ȫ▒Ĳ▒▒▒▒▒
[INFO] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/main/java/org/bukkit/World.java: ▒й▒▒▒ϸ▒▒Ϣ, ▒▒ʹ▒▒ -Xlint:unchecked ▒▒▒±▒▒롣
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ paper-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-API\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ paper-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 49 source files to C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-API\target\test-classes
[INFO] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/test/java/org/bukkit/NamespacedKeyTest.java: ĳЩ▒▒▒▒▒ļ▒ʹ▒û򸲸▒▒▒▒ѹ▒ʱ▒▒ API▒▒
[INFO] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/test/java/org/bukkit/NamespacedKeyTest.java: ▒й▒▒▒ϸ▒▒Ϣ, ▒▒ʹ▒▒ -Xlint:deprecation ▒▒▒±▒▒롣
[INFO] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/test/java/org/bukkit/plugin/messaging/StandardMessengerTest.java: ĳЩ▒▒▒▒▒ļ▒ʹ▒▒▒▒δ▒▒▒▒▒򲻰▒ȫ▒Ĳ▒▒▒▒▒
[INFO] /C:/Users/14868/Desktop/Akarin-Project/Akarin/work/Paper/Paper-API/src/test/java/org/bukkit/plugin/messaging/StandardMessengerTest.java: ▒й▒▒▒ϸ▒▒Ϣ, ▒▒ʹ▒▒ -Xlint:unchecked ▒▒▒±▒▒롣
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ paper-api ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ paper-api ---
[INFO] Building jar: C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-API\target\paper-api-1.12.2-R0.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-shade-plugin:3.1.0:shade (default) @ paper-api ---
[INFO] Including com.mojang:authlib:jar:1.5.25 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.10 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.4 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.5 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-api:jar:2.8.1 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-core:jar:2.8.1 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including com.googlecode.json-simple:json-simple:jar:1.1.1 in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:1.3.9 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:21.0 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.8.0 in the shaded jar.
[INFO] Including org.yaml:snakeyaml:jar:1.19 in the shaded jar.
[INFO] Including net.md-5:bungeecord-chat:jar:1.12-SNAPSHOT in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.25 in the shaded jar.
[INFO] Including org.ow2.asm:asm:jar:6.1.1 in the shaded jar.
[INFO] Including org.ow2.asm:asm-commons:jar:6.1.1 in the shaded jar.
[INFO] Including org.ow2.asm:asm-tree:jar:6.1.1 in the shaded jar.
[INFO] Including org.ow2.asm:asm-analysis:jar:6.1.1 in the shaded jar.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[INFO] Attaching shaded artifact.
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ paper-api ---
[INFO] Installing C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-API\target\paper-api-1.12.2-R0.1-SNAPSHOT.jar to C:\Users\14868\.m2\repository\com\destroystokyo\paper\paper-api\1.12.2-R0.1-SNAPSHOT\paper-api-1.12.2-R0.1-SNAPSHOT.jar
[INFO] Installing C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-API\pom.xml to C:\Users\14868\.m2\repository\com\destroystokyo\paper\paper-api\1.12.2-R0.1-SNAPSHOT\paper-api-1.12.2-R0.1-SNAPSHOT.pom
[INFO] Installing C:\Users\14868\Desktop\Akarin-Project\Akarin\work\Paper\Paper-API\target\paper-api-1.12.2-R0.1-SNAPSHOT-shaded.jar to C:\Users\14868\.m2\repository\com\destroystokyo\paper\paper-api\1.12.2-R0.1-SNAPSHOT\paper-api-1.12.2-R0.1-SNAPSHOT-shaded.jar
[INFO]
[INFO] -------------------< com.destroystokyo.paper:akarin >-------------------
[INFO] Building Akarin 1.12.2-R0.4-SNAPSHOT                               [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Paper-Parent dev-SNAPSHOT .......................... SUCCESS [  0.174 s]
[INFO] Paper-API 1.12.2-R0.1-SNAPSHOT ..................... SUCCESS [  7.155 s]
[INFO] Akarin 1.12.2-R0.4-SNAPSHOT ........................ FAILURE [  0.079 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.471 s
[INFO] Finished at: 2022-03-15T20:02:21+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project akarin: Could not resolve dependencies for project com.destroystokyo.paper:akarin:jar:1.12.2-R0.4-SNAPSHOT: Failed to collect dependencies at io.akarin:legacylauncher:jar:1.26: Failed to read artifact descriptor for io.akarin:legacylauncher:jar:1.26: Could not transfer artifact io.akarin:legacylauncher:pom:1.26 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [elmakers-repo (http://maven.elmakers.com/repository/, default, releases+snapshots), nallar-repo (http://repo.nallar.me/, default, releases+snapshots), josephworks (http://repo.josephworks.net/repository/maven-public/, default, releases+snapshots)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :akarin
Failed to build Akarin

commands:
git clone https://github.com/Akarin-project/Akarin -b ver/1.12.2 --recursive; cd Akarin; ./scripts/inst.sh --setup --fast

**Comment by ghost** [comment]
should use maven<=3.6.3 which allows http connection.

**Comment by josephworks** [comment]
No, this is an issue with the pom and I will fix this ASAP. We shouldn't be using HTTP or old versions of Maven.

**Comment by FatSaw** [comment]
I have fixed the build.  But I'm sure I did it wrong.  My task was to build akarin 1.12.2 at any cost.
 https://github.com/FatSaw/Akarin

**Comment by josephworks** [comment]
It looks good to me. Please do a pull request when ready and I will review it again and accept it.
