### ISSUE TITLE
[1.12.2] Crash when generating a world

### ISSUE THREAD

**Issue by Netscape7** [Akarin-project/Akarin#226]
When I run Akarin, it crashes with world generation. Is there a workaround?
[crash-2022-06-28_23.32.05-server.txt](https://github.com/Akarin-project/Akarin/files/9009052/crash-2022-06-28_23.32.05-server.txt)

**Comment by josephworks** [comment]
What version of Akarin 1.12.2 are you using?

Also, please send full log.

**Comment by Netscape7** [comment]
[latest.log](https://github.com/Akarin-project/Akarin/files/9019761/latest.log)
Is this alright?
The version you are using is # 289.

**Comment by ghost** [comment]
This issue has been fixed in build 291
