### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MClausz** [Akarin-project/Akarin#23]
https://pastebin.com/imKCHrgd
https://pastebin.com/3D9Ura1Q

**Comment by Wesley-VanNeck** [comment]
Plugin issue

**Comment by MClausz** [comment]
@Wesley-VanNeck you can't blame the plugin, ProtocolSupport runs fine on PaperSpigot.
The issue happened in the class EntityTrackerEntry, ProtocolSupport's SpigotEntityTrackerEntry class just extends the original EntityTrackerEntry class.
And in the second log the server freeze while ticking (MinecraftServer.D)

**Comment by cakoyo** [comment]
We have locks on EntityTracker but ProtocolSupport's version doesn't have, I think it causes the issue.
