### ISSUE TITLE
告示牌材质不显示的问题（git-Akarin-"e912498"）

### ISSUE THREAD

**Issue by Redroadsl** [Akarin-project/Akarin#235]
[12:39:01 INFO]: This server is running Akarin version git-Akarin-"e912498" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
使用这个版本的Akarin服务端，在客户端里显示不出告示牌的材质和文字。
错误重现：
更新了新版Akarin git-Akarin-"e912498"
启动服务器，打开客户端，登录
告示牌和上面的文字全部消失，但是告示牌的轮廓还在。
生存模式轻轻撸一撸告示牌，材质回来了，但是文字依然不在，重新进入服务器，告示牌又都消失了。
换高版本mc（装了版本兼容插件），问题依旧。

从新版换回老版Akarin（git-Akarin-5fe9361），老版本的Akarin服务端并不会出现这个问题，所以不是存档的问题。

这很重要，望尽快解决。

**Comment by josephworks** [comment]
Please send logs and plugin versions

**Comment by Redroadsl** [comment]
Version with bug: git-Akarin-"e912498"
**Plug-ins:**

1. BungeeGuard v1.3
2. Chairs 
3. ChestCommands 4.0.3
4. Custom_joinLeftMessages 
5. Essentials 2.17.2.42
6. HolographicDisplay 3.0.0
7. InventoryFull 1.8
8. LaggRemover 2.0.5
9. NoCheatPlus latest3.16.0
10. Vault 1.7.3-b131
11. VisVersion 4.5.1
12. WorldEdit 6.1.9

Log:
There isn’t any difference between the logs from this version and the old version (except time)

Bug version log:

[2023-01-08-2.log](https://github.com/Akarin-project/Akarin/files/10368940/2023-01-08-2.log)

**Comment by josephworks** [comment]
Please make a copy of your server and see if the issue occurs without the ChestCommands plugin.

**Comment by Redroadsl** [comment]
Oh no. The problem remains.

**Comment by Redroadsl** [comment]
Screenshots
![98B644B9-DDF1-4A25-B816-D37F9A8792C8](https://user-images.githubusercontent.com/50506568/211458297-4e796ea3-725d-486e-bae0-4f44db7102cc.jpeg)
![2432ECC9-20AE-49BD-9641-25BAD4FBAC40](https://user-images.githubusercontent.com/50506568/211458304-ac0ad45c-f99f-4f70-b16b-9303f9f49d45.jpeg)

**Comment by josephworks** [comment]
@Redroadsl Please test out the latest release to see if this fixes your issue:
https://github.com/Akarin-project/Akarin/releases/tag/1.12.2-R0.4.4
