### ISSUE TITLE
The problem with the plates on this core!

### ISSUE THREAD

**Issue by Diskanskiy** [Akarin-project/Akarin#236]
Hi, I installed the Akarin kernel on my server, I was very shocked by the results of TPS, and ping, even better than Paper, and most importantly - it can be translated to your language, and patching, but there was one problem. The plates do not work when I want to create a new one, and I write the text - it does not appear on it, but in the console writes this: Player User123 just tried to change non-editable sign

What to do?

**Comment by FatSaw** [comment]
Core version?

**Comment by Diskanskiy** [comment]
> Core version?

1.12.2 (0.4.3)

**Comment by FatSaw** [comment]
https://github.com/Akarin-project/Akarin/blob/7dcfc130d2175cd435e7cc69ef7c1376997e4b6d/sources/src/main/java/net/minecraft/server/PlayerConnection.java#L2227-L2239

**Comment by josephworks** [comment]
This should be fixed, please test out the latest release:
https://github.com/Akarin-project/Akarin/releases/tag/1.12.2-R0.4.4
