### ISSUE TITLE
Question: Is EntityTracker.updatePlayers() multi threaded?

### ISSUE THREAD

**Issue by MClausz** [Akarin-project/Akarin#24]
Which regular PaperSpigot, when I open timings of my server, there always be world - tracker statge 1 causes TPS drop.
Currently I can't use Akarin because it's unstable, it crash after about a hour, I want to know if the method above multi threaded, I tried looking in to your code and there is still timings in that method.

**Comment by cakoyo** [comment]
No, the method will be invoked in the main thread. Akarin will skip all timings called asynchronously, remove all callers will make our codes hard to maintain.

**Comment by MClausz** [comment]
I tried decompiling and make that method multi-threaded, make all related maps/collections thread-safe, at first it works fine with the older build of paper (the build that uploaded around 30 May), but with the most recent build of paper, I'm facing an issue that sometime a player's EntityTrackerEntry doesn't get updated, they will become invisible to other players.
This is how my code looks like
https://pastebin.com/bBK0vEHs

**Comment by Leymooo** [comment]
I think its a bad idea to create a new thread for each method call.

**Comment by MClausz** [comment]
@Leymoo I put them to a synchronized lock so that will be fine

**Comment by cakoyo** [comment]
I noticed the changes in #9cfe108 cause many entity update issues, just reverted it.

**Comment by cakoyo** [comment]
Made this parallel again, without significant issues so far.
