### ISSUE TITLE
Bad Server Link in README.

### ISSUE THREAD

**Issue by Redroadsl** [Akarin-project/Akarin#248]
website "fairserver.ru" is not properly working. It's now linking to a criminal website.
We need Minecraft, not drug.

**Comment by josephworks** [comment]
Where do you see this link?

**Comment by Redroadsl** [comment]
Akarin1.16.5 Readme.md in demo server
![Screenshot_20240808_232607_org mozilla firefox](https://github.com/user-attachments/assets/31c45872-7c5b-44e1-b06a-f2921eb6a11c)

**Comment by josephworks** [comment]
It was in the 1.14, 1.15, and 1.16 readme too. I removed it from all of them.
