### ISSUE TITLE
emm编译失败

### ISSUE THREAD

**Issue by xiaonian233** [Akarin-project/Akarin#3]
![image](https://user-images.githubusercontent.com/21072615/40882470-653f4be0-6715-11e8-92ca-830964d43a8f.png)
![image](https://user-images.githubusercontent.com/21072615/40882471-74a257c6-6715-11e8-913b-67345d9adc9f.png)
![image](https://user-images.githubusercontent.com/21072615/40882472-7bd673b0-6715-11e8-92e9-b98f599b19de.png)
把仓库换成aliyun的了不知道是否有影响

**Comment by cakoyo** [comment]
应当已经修复
