### ISSUE TITLE
Update plz to 1.13

### ISSUE THREAD

**Issue by wesleyvanneck** [Akarin-project/Akarin#31]
Am sorry if this spam but other multireaded forks are really fast dead like torch so plz  updated it to 1.13

**Comment by cakoyo** [comment]
After Spigot and Paper updated to 1.13, we will do. Actually, Akarin is the continuation of Torch.

**Comment by Wesley-VanNeck** [comment]
@cakoyo can you make a dev branch for 1.13

**Comment by cakoyo** [comment]
Updated
