### ISSUE TITLE
fix 50 millis delay between hit and velocity

### ISSUE THREAD

**Issue by Awamo** [Akarin-project/Akarin#37]
to fix it, go into networkmanager class, and override this method:
            if (packet.a()) {
(                ((Packet) packet).a(this.m); for you)
and set it to true.

**Comment by cakoyo** [comment]
What is `packet.a()`? I didn't find that method, could you point it a bit more clear?

**Comment by Awamo** [comment]
NetworkManager -> protected void a

**Comment by MClausz** [comment]
There is a update velocity code block in EntityTrackerEntry#track (` if (this.tracker.velocityChanged)`), to fix this issue I move them to the main thread.
Also calling PlayerVelocityEvent asynchronously may cause server crash.

**Comment by cakoyo** [comment]
@Awamo so what is 'set to true'?? I didn't saw any method accept a `boolean` argument there nor return type.

**Comment by cakoyo** [comment]
@MClausz I didn't call that method asynchronously, and since its caller is `EntityTracker#updatePlayers()` this method will be called every tick for every world, I don't think there is any extra delay compared to vanilla.

**Comment by Awamo** [comment]
so go to Packet Class and you will get a boolean at the end of the code (i think boolean a) and you will get a return, just set it to true, and override the method ;)
sorry for answering so late

**Comment by cakoyo** [comment]
@Awamo which packet class? in networkmanager it's a interface....

**Comment by cakoyo** [comment]
I checked it again, there is ` default a()` in 1.13.2, but not in 1.12.2. However, it's only used for exception handlers. I also did some test, idk how this thing reduces the delay.
