### ISSUE TITLE
Jenkins and CircleciCI no longer update new builds?

### ISSUE THREAD

**Issue by MClausz** [Akarin-project/Akarin#39]
Last build was 7 days ago

**Comment by cakoyo** [comment]
Jenkins didn't organize our branch rename, I will contact the owner... as for CircleCI, check [here](https://circleci.com/gh/Akarin-project/Akarin/tree/ver%2F1.12.2).

**Comment by cakoyo** [comment]
Unfortunately, our Jenkins was blocked by China national firewall (GFW), so just use CircleCI is fine before we switch to a new host.

**Comment by wesleyvanneck** [comment]
@cakoyo your Jenkins works Just fine i can ping it

**Comment by cakoyo** [comment]
@wesleyvanneck however, we cannot access it from China without proxies (included the website owner), so we have to move to another host since the website is generally provided for China users...

**Comment by MClausz** [comment]
@cakoyo artifacts tab isn't visivle to me
https://i.imgur.com/YsGvX3H.png

**Comment by cakoyo** [comment]
@MClausz  Login..
