### ISSUE TITLE
HUGE ERROR

### ISSUE THREAD

**Issue by FresterEx** [Akarin-project/Akarin#4]
I have error when use timings! 
Pastebin: https://pastebin.com/afERj4nP

And error save chunk & threw entity! pls fixed
Some plugin is not compatible!!!

Latest version of Akarin-1.12.2!

**Comment by cakoyo** [comment]
If you still suffer this, please use #68 in cricle-ci or #65 in jenkins

**Comment by FresterEx** [comment]
Your plugin not compatible with spigot plugins like AAC pls fixed. I very need multi-threads but your plugin have too much error!

**Comment by cakoyo** [comment]
any log or crash-report?

**Comment by FresterEx** [comment]
Yes but i have remove

**Comment by FresterEx** [comment]
Sorry, i have question!
http://ci.ilummc.com/job/Paper/ (Does Paper in this website is using multi-threads? i don't know)

**Comment by cakoyo** [comment]
No, it's a third-party jenkins and Akarin is based on Paper(you can find paper.yml)

**Comment by FresterEx** [comment]
You can added a single Paperspigot using Multi-threads? because akarin not compatible with spigot plugin :(( some time having error

**Comment by cakoyo** [comment]
No, because the compatible issues are actually caused by multithreading. You'd better provide logs and a list of plugins that cannot be use.

**Comment by FresterEx** [comment]
No, i don't think so, i think you decompile the .jar have error. In country, my friend have decompile sucess using Multi-threads for Paperspigot and no have error! i don't know why but i need you make better!

**Comment by FresterEx** [comment]
[09:09:49] [Netty Server IO #2/WARN]: [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[AbstractChannel$AbstractUnsafe.class:git-Akarin-"02eda01"]

**Comment by cakoyo** [comment]
You should paste all traces, not replace them with '~'

**Comment by cakoyo** [comment]
why not use pastebin

**Comment by cakoyo** [comment]
> No, i don't think so, i think you decompile the .jar have error. In country, my friend have decompile sucess using Multi-threads for Paperspigot and no have error! i don't know why but i need you make better!
decompile? it's normal if you decompile the jar and see errors

**Comment by FresterEx** [comment]
The error spam log is very small in top, i think not need to use pastebin

**Comment by cakoyo** [comment]
Does the warn keeping spam your console? If not, you can ignore it (sometimes when a player disconnect server forcely, the warn may occurs)
btw, any way to reproduce?

**Comment by FresterEx** [comment]
Some time my Console have spam when player connect..

**Comment by FresterEx** [comment]
Please make it better

**Comment by cakoyo** [comment]
I'll try..

**Comment by cakoyo** [comment]
The bleeding modify of network was removed. Reopen an issue, if you suffer new errors/bugs.
