### ISSUE TITLE
[1.13]Server has stopped responding!

### ISSUE THREAD

**Issue by SomeBottle** [Akarin-project/Akarin#44]
Error日志我加在附件里面了
服务器没有预兆地停止响应，插件兼容性已经测试过。
[errorlog#3.txt](https://github.com/Akarin-project/Akarin/files/2269760/errorlog.3.txt)

**Comment by SomeBottle** [comment]
另外附上CrashReport
[crash-2018-08-08_06.52.40-server.txt](https://github.com/Akarin-project/Akarin/files/2269775/crash-2018-08-08_06.52.40-server.txt)

**Comment by cakoyo** [comment]
No idea why you open an issue since you already told me, the latest build should fixed.
