### ISSUE TITLE
Base Akarin off of tacospigot instead of paperspigot

### ISSUE THREAD

**Issue by WhyDoWeWonder** [Akarin-project/Akarin#48]
TacoSpigot is an even more optimized version of paperspigot, with massive improvements on armorstands, TNT, and hoppers. I think it would make sense to base Akarin off of TacoSpigot rather than Paper, unless there are some incompatibility issue., I'm working on putting a build together right now, just posting this here in case  you've already know this won't work.

**Comment by CBM1014** [comment]
We don't think the advantages of doing this can make up for the hardship of this matter. Taco has many problems can't be solved in time, even though there were many improvements. We are looking forward to your completing this work. Before that, we will not work on it.
![:thinking:](https://public-readspace.oss-cn-beijing.aliyuncs.com/thinking.png)

**Comment by WhyDoWeWonder** [comment]
I tried this and it just completely failed, advice to anyone who might try this in the future, it's not worth it.
