### ISSUE TITLE
1.13: NPE in server tick loop

### ISSUE THREAD

**Issue by jason920612** [Akarin-project/Akarin#52]
Plugins (33): AntiCrash, BossShop, ColorMOTD, CoreProtect, DiscordSRV, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, GroupManager, GuiShopManager, iConomy, LaggRemover, LockettePro, MobHeads, MoneyDrop, Multiverse-Core, MysqlEconomyBank, PlaceholderAPI, PlayerPoints, PlotSquared, ProtocolLib, PvPManager, QuickShop, RandomTeleportPro, React, Residence, TimeIsMoney, TitleManager, Vault, VipZero, WorldCommandBlock, WorldEdit
這個崩潰訊息經常出現在服務器我不知道他是如何觸發的[https://pastebin.com/JHgd2XhS](url)崩潰報告

**Comment by cakoyo** [comment]
信息不足，请在开服参数内添加 `-XX:-OmitStackTraceInFastThrow`，以便下次反馈。

**Comment by tsao-chi** [comment]
(1.13 support has been dropped)
