### ISSUE TITLE
how to download

### ISSUE THREAD

**Issue by kit8379** [Akarin-project/Akarin#53]
I went in https://circleci.com/gh/Akarin-project/Akarin/tree/ver/1.12.2 already but i still don't know how to download it.

**Comment by SomeBottle** [comment]
Please check the README file.You need to learn something.

**Comment by cakoyo** [comment]
You can get the latest 1.12.2 direct link from [here](https://circleci.com/api/v1.1/project/github/Akarin-project/Akarin/latest/artifacts?circle-token48df11636a49afecd9e1cebab3e135d7f652795f&branch=ver/1.12.2&filter=successful) now and future, you'd better ask in discord instead of spam issues.
