### ISSUE TITLE
Voucher plugin causes server crash

### ISSUE THREAD

**Issue by Jodmc** [Akarin-project/Akarin#59]
I was planning on using the Vouchers plugin to make perk items that give people a specific permission when they use it, however I've run into a bit of a problem... It seems that the server crashes every time I right-click to use a perk while looking at air. It doesn't crash the server if I open it while looking at a block.

Here's the message that comes up when the server crashes: https://pastebin.com/QG4RWMUd
As you can see on lines 1-2, I can use the plugin commands and it applies the reward properly, however it crashes after applying it (line 3+).

We're using Akarin 1.12 I believe, if that helps.

**Comment by cakoyo** [comment]
Can you reproduce this on Paper/Spigot?

**Comment by Winninq** [comment]
> Can you reproduce this on Paper/Spigot?

We kind of just left that plugin be and had our developer make a custom voucher plugin for us.

**Comment by josephworks** [comment]
It appears that this issue has been resolved!
