### ISSUE TITLE
 How long will it take to update?

### ISSUE THREAD

**Issue by LXSN** [Akarin-project/Akarin#63]
I'm sorry to trouble you. When to support 1.13.2, I really need 1.13.2 support.

**Comment by hempflower** [comment]
I don't think the author will be upgraded.

**Comment by LXSN** [comment]
> I don't think the author will be upgraded.

why

**Comment by hempflower** [comment]
@LXSN Because forge is not stable right now

**Comment by WesleyVanNeck** [comment]
@hempflower it dont forge this is a paper fork

**Comment by WesleyVanNeck** [comment]
If you wanth updated version am busy with it https://github.com/WesleyVanNeck/Akarin

**Comment by liach** [comment]
there is akarinforge though

**Comment by cakoyo** [comment]
I finally decided back to use the source codes directly, since mixin making changes harder and through a jump-project to update upstream. 1.13 changed a lot, we may have to start from zero.
