### ISSUE TITLE
Can't load plugin HolographicDisplays 

### ISSUE THREAD

**Issue by ArtNRG** [Akarin-project/Akarin#68]
The plugin can't be loaded using Akarin version git-Akarin-"4c4d318" (MC: 1.13.2)
Tested with Paper build 564 (MC: 1.13.2) - all is OK.
Error log: https://pastebin.com/raw/yaN70M1T
The plugin can be downloaded here: https://dev.bukkit.org/projects/holographic-displays/files/2652670
Or here: https://ci.filoghost.me/job/HolographicDisplays/

**Comment by WesleyVanNeck** [comment]
Works fine for me

**Comment by ArtNRG** [comment]
Hm... Tried to load only HolographicDisplays - it works. That's really odd. Here is the full log, maybe someone can point me where is the problem
https://pastebin.com/raw/pwUNHetZ

**Comment by huynhqtienvtag** [comment]
Set "modified-server-brand-name" in akarin.yml to "Paper"
Check if that works

**Comment by ArtNRG** [comment]
@huynhqtienvtag thank you, the setting "modified-server-brand-name" is helped me to run the plugin.
