### ISSUE TITLE
Can't download Akarin

### ISSUE THREAD

**Issue by arturek1666** [Akarin-project/Akarin#69]
https://circleci.com/gh/Akarin-project/Akarin
Warning: Your project is using CircleCI 1.0 and will stop building on March 15, 2019. Update remaining projects to CircleCI 2.0 to continue building. Learn more.

**Comment by WesleyVanNeck** [comment]
You need login in google or githu first

**Comment by arturek1666** [comment]
![Untitled](https://user-images.githubusercontent.com/1558228/54426514-f9a60780-470f-11e9-918e-b90052000077.png)
I still don't see where to download and the rebuild it say I have no permission

**Comment by WesleyVanNeck** [comment]
really use artifacts folder dam how dum can people be

**Comment by arturek1666** [comment]
Well I am sorry that I never use this site before. But calling me dum it's not nice. Do you think that a person that see a new website in first time can understand what is where well the answer is NO.

**Comment by WesleyVanNeck** [comment]
no but you can read clearly and am mean i know that

**Comment by arturek1666** [comment]
By the way thx for help. I know you call me dum but If I would not say that I would be not a nice person xD.

**Comment by arturek1666** [comment]
The issue was resolved.
