### ISSUE TITLE
EntityTracker safety issues

### ISSUE THREAD

**Issue by disqetow** [Akarin-project/Akarin#7]
07.06 08:10:06 [Server] ERROR This crash report has been saved to: /Server_Spigot/./crash-reports/crash-2018-06-07_08.10.06-server.txt
07.06 08:10:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[MinecraftServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[DedicatedServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:1871) ~[MinecraftServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.tickWorld(MinecraftServer.java:1808) ~[MinecraftServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:328) ~[WorldServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:214) ~[PlayerChunkMap.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerChunk.b(PlayerChunk.java:152) ~[PlayerChunk.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:260) ~[EntityTracker.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_151]
07.06 08:10:06 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_151]
07.06 08:10:06 [Server] INFO java.util.ConcurrentModificationException: null
07.06 08:10:06 [Server] ERROR Cause of unexpected exception was
07.06 08:10:06 [Server] INFO ... 5 more
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.tickWorld(MinecraftServer.java:1808) ~[MinecraftServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:328) ~[WorldServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:214) ~[PlayerChunkMap.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerChunk.b(PlayerChunk.java:152) ~[PlayerChunk.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:260) ~[EntityTracker.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_151]
07.06 08:10:06 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_151]
07.06 08:10:06 [Server] INFO Caused by: java.util.ConcurrentModificationException
07.06 08:10:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[MinecraftServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[DedicatedServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:1871) ~[MinecraftServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.tickWorld(MinecraftServer.java:1817) ~[MinecraftServer.class:git-Akarin-"02eda01"]
07.06 08:10:06 [Server] INFO net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world
07.06 08:10:06 [Server] ERROR Encountered an unexpected exception

**Comment by disqetow** [comment]
I use new build just still crash like this

**Comment by cakoyo** [comment]
The fix was removed temporarily because some reason, I will readd it.

**Comment by cakoyo** [comment]
btw, what plugins ae using?

**Comment by disqetow** [comment]
what you mean ae?

**Comment by disqetow** [comment]
Is this error about timing?

**Comment by cakoyo** [comment]
(ae = are you)
From my research, I eventually don't think this is an issue caused by the server itself, there is just a plugin causes this, but we can't blame the plugin, we also access the field from non-main thread, this means that the plugin can running in Spigot or Paper without errors. I'll try to find a workaround.

**Comment by cakoyo** [comment]
Not timing.

**Comment by cakoyo** [comment]
Try lastest build

**Comment by cakoyo** [comment]
Does this still happen?

**Comment by cakoyo** [comment]
The current workaround isn't perfect, we should go deeper anyway

**Comment by cakoyo** [comment]
Furthermore, it's still hard to say whether this was caused by a plugin
