### ISSUE TITLE
IllegalArgumentException console error - ProtocolLib

### ISSUE THREAD

**Issue by ArtNRG** [Akarin-project/Akarin#77]
https://pastebin.com/raw/fehFCr4U

git-Akarin-"4c4d318"
ProtocolLib version 4.4.0

**Comment by shinohara-rin** [comment]
update your server to the latest version will solve the problem

for detailed information see #70

**Comment by ArtNRG** [comment]
Thanks, now I see. I updated the test server jar and forgot to update jar on the main server.
