### ISSUE TITLE
Invisible Mobs + Invincible Mobs

### ISSUE THREAD

**Issue by Kyrobi** [Akarin-project/Akarin#78]
Akarin version ecdda0e

Note: I have tested this on Paper (Switched to using it for 3 days) and the following issue does not occur.

**Invisible mob:** Sometimes mob would become completely invisible. I have only noticed this on mobs. When going into wild, I'll rarely randomly get attacked be some for of mythical entity. When I died, it said that I was killed by a zombie. Recently, more and more players have reported encountering invisible entities. 

This can be observed often when players warp to an area that has villagers as admin shop. Sometimes when you warp there, the villagers would be completely invisible. Going away from the area and warping back sometimes fixes the invisible villagers. 

I have tried to record a video of natural mobs that are invisible, but the chances are just so random and I wasn't able to get it on video. There's also no error in console.

_Edit: About 10 minutes ago, a player reported a grief as some of his armor stand (with enchanted armor) were gone. A few minutes later when he went back to the house, all of the armor stand reappeared again._

I don't know if this is related to the invisible mob, but another thing is **invincible mob**. When mobs are killed, there's also a rare chance that it'll show the death animation (mob is red and following to the ground) but the mob won't die. It'll be continuously stuck in a state of dying. While in this state, the mob is invincible. You can't even hit it. Arrows will bounce off. However, that mob is still able to follow you and attack you. Following in lava won't kill the mob either. Only way to get rid of this is the unload the area.

This was first observed when I went into a slime chunk and spammed my bow at all the slimes. After I killed about 30~ slimes, one of them turned into an undying one (stuck in death animation).

**Comment by cakoyo** [comment]
It's really odd...

**Comment by Ghost-chu** [comment]
I see it in Paper before, i don't know why it will happend.
And in some build of Paper, this problem nolonger exist.

**Comment by Kyrobi** [comment]
> Akarin version [ecdda0e](https://github.com/Akarin-project/Akarin/commit/ecdda0e0c17844f7789d387918cfd98d0199239e)
> 
> Note: I have tested this on Paper (Switched to using it for 3 days) and the following issue does not occur.
> 
> **Invisible mob:** Sometimes mob would become completely invisible. I have only noticed this on mobs. When going into wild, I'll rarely randomly get attacked be some for of mythical entity. When I died, it said that I was killed by a zombie. Recently, more and more players have reported encountering invisible entities.
> 
> This can be observed often when players warp to an area that has villagers as admin shop. Sometimes when you warp there, the villagers would be completely invisible. Going away from the area and warping back sometimes fixes the invisible villagers.
> 
> I have tried to record a video of natural mobs that are invisible, but the chances are just so random and I wasn't able to get it on video. There's also no error in console.
> 
> _Edit: About 10 minutes ago, a player reported a grief as some of his armor stand (with enchanted armor) were gone. A few minutes later when he went back to the house, all of the armor stand reappeared again._
> 
> I don't know if this is related to the invisible mob, but another thing is **invincible mob**. When mobs are killed, there's also a rare chance that it'll show the death animation (mob is red and following to the ground) but the mob won't die. It'll be continuously stuck in a state of dying. While in this state, the mob is invincible. You can't even hit it. Arrows will bounce off. However, that mob is still able to follow you and attack you. Following in lava won't kill the mob either. Only way to get rid of this is the unload the area.
> 
> This was first observed when I went into a slime chunk and spammed my bow at all the slimes. After I killed about 30~ slimes, one of them turned into an undying one (stuck in death animation).

I think this issue can be closed. I believe the issue is with the plugin called "React", a lag management plugin. When I was using Paper to do the some testing, I had react enabled. 2 days later, someone reported seeing an invincible mob again.

Since React has been disabled, there's no report so far regarding this.

**Comment by cakoyo** [comment]
Ok, React is a weird plugin.
