### ISSUE TITLE
b83eb29 Crash

### ISSUE THREAD

**Issue by Kyrobi** [Akarin-project/Akarin#79]
Build: b83eb29

Server will just randomly crash when some players join. 

Crash log: https://pastebin.com/uMdiNheb

**Comment by Ghost-chu** [comment]
https://ci.melon.cat/job/Akarin/45/artifact/akarin-1.13.2-b45.jar

Please try this build, check this issue is still exist.

**Comment by cakoyo** [comment]
Can you test the latest build?

**Comment by cakoyo** [comment]
Confirm fixed.
