### ISSUE TITLE
1.13.2: API version doesn't display properly

### ISSUE THREAD

**Issue by megoesrawr** [Akarin-project/Akarin#83]
I'm getting this error:
`20.04 03:27:15 [Server] ERROR Error occurred while enabling Essentials v2.16.1.0 (Is it up to date?)
20.04 03:27:15 [Server] INFO java.lang.IllegalArgumentException: Unknown-Version is not in valid version format. e.g. 1.8.8-R0.1
20.04 03:27:15 [Server] INFO at com.earth2me.essentials.utils.VersionUtil$BukkitVersion.fromString(VersionUtil.java:52) ~[?:?]
20.04 03:27:15 [Server] INFO at com.earth2me.essentials.utils.VersionUtil.getServerBukkitVersion(VersionUtil.java:30) ~[?:?]
20.04 03:27:15 [Server] INFO at com.earth2me.essentials.utils.VersionUtil.isServerSupported(VersionUtil.java:36) ~[?:?]
20.04 03:27:15 [Server] INFO at com.earth2me.essentials.Essentials.onEnable(Essentials.java:175) ~[?:?]
20.04 03:27:15 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:426) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:444) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:358) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:611) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:573) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:434) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:317) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:790) ~[spigot.jar:git-Akarin-"d419e8b"]
20.04 03:27:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191-1-ojdkbuild]
20.04 03:27:15 [Server] INFO [Essentials] Disabling Essentials v2.16.1.0`
I'm on the newest version as well.

**Comment by CBM1014** [comment]
I found an issue about getting the API version.
The API version doesn't display properly.

**Comment by megoesrawr** [comment]
Ah. Any ETA on the fix?
