### ISSUE TITLE
OP Function issue

### ISSUE THREAD

**Issue by HeliosOps** [Akarin-project/Akarin#84]
Hi, I am facing a issue with the latest build Akarin 1.13.2.
My server is running in BungeeCord(online-mode false) and Akarin 1.13.2 environment.

Then I give op to myself in console /op XXXXX
Then console display:
20.04 17:44:26 [Server] INFO Made XXXXX a server operator

After that, XXXXX in the server no have any permission and not saw any operated message.

**Comment by WesleyVanNeck** [comment]
same issue

**Comment by cakoyo** [comment]
I can't reproduce the issue in offline mode, please ensures that `bungee-online-mode` in paper.yml is false if ur bungeecord is offline too.

**Comment by HeliosOps** [comment]
Problem solve, thank you. XD
