### ISSUE TITLE
Mythic Mobs Issues

### ISSUE THREAD

**Issue by WhyDoWeWonder** [Akarin-project/Akarin#87]
Not sure what's wrong here, I think it's mob-spawning but this hasn't happened with paper.

https://hastebin.com/ayodapobar.php

**Comment by cakoyo** [comment]
I believe this is a plugin issue since MythicMobs access the scoreboard from off-main-thread and scoreboard is not thread-safe. However, I found it can be optimized and reduce the happening of the safety issue.
