### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by WhyDoWeWonder** [Akarin-project/Akarin#90]
The server works fine, no errors in console, but all clients crash with something like this

`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 5/6/19 1:53 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Byte cannot be cast to fd
	at alz.R_(SourceFile:596)
	at axy.a(SourceFile:1243)
	at axy.g(SourceFile:1218)
	at axy.o_(SourceFile:1100)
	at cft.m(SourceFile:1281)
	at cft.c(SourceFile:821)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at alz.R_(SourceFile:596)
	at axy.a(SourceFile:1243)
	at axy.g(SourceFile:1218)

-- Entity being ticked --
Details:
	Entity Type: minecraft:armor_stand (alz)
	Entity ID: 0
	Entity Name: 
	Entity's Exact location: -289.50, 62.45, 3400.50
	Entity's Block location: World: (-290,62,3400), Chunk: (at 14,3,8 in -19,212; contains blocks -304,0,3392 to -289,255,3407), Region: (-1,6; contains chunks -32,192 to -1,223, blocks -512,0,3072 to -1,255,3583)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at axy.o_(SourceFile:1100)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['LordofLightning'/10048, l='MpServer', x=-366.18, y=67.00, z=3447.31]]
	Chunk stats: MultiplayerChunkCache: 138, 138
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 141844 game time, 22326550 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 114 total; [ctj['LordofLightning'/10048, l='MpServer', x=-366.18, y=67.00, z=3447.31], alz[''/0, l='MpServer', x=-289.50, y=62.45, z=3400.50], aep['Area Effect Cloud'/10243, l='MpServer', x=-304.00, y=0.00, z=3392.00], ame['Painting'/10254, l='MpServer', x=-303.00, y=64.50, z=3395.03], amb['Item Frame'/10255, l='MpServer', x=-302.50, y=64.50, z=3402.97], aep['Area Effect Cloud'/10273, l='MpServer', x=-304.00, y=0.00, z=3488.00], aep['Area Effect Cloud'/10309, l='MpServer', x=-304.00, y=0.00, z=3504.00], aep['Area Effect Cloud'/10071, l='MpServer', x=-368.00, y=0.00, z=3440.00], ame['Painting'/10184, l='MpServer', x=-306.97, y=65.00, z=3401.50], aep['Area Effect Cloud'/10072, l='MpServer', x=-368.00, y=0.00, z=3424.00], ame['Painting'/10185, l='MpServer', x=-306.97, y=65.00, z=3397.00], aep['Area Effect Cloud'/10073, l='MpServer', x=-384.00, y=0.00, z=3424.00], ame['Painting'/10186, l='MpServer', x=-306.97, y=65.00, z=3406.00], aep['Area Effect Cloud'/10074, l='MpServer', x=-384.00, y=0.00, z=3440.00], aep['Area Effect Cloud'/10075, l='MpServer', x=-384.00, y=0.00, z=3456.00], aep['Area Effect Cloud'/10076, l='MpServer', x=-368.00, y=0.00, z=3456.00], aep['Area Effect Cloud'/10077, l='MpServer', x=-352.00, y=0.00, z=3456.00], aep['Area Effect Cloud'/10078, l='MpServer', x=-352.00, y=0.00, z=3440.00], ann['Skeleton'/10079, l='MpServer', x=-341.50, y=15.00, z=3441.50], ann['Skeleton'/10080, l='MpServer', x=-340.27, y=16.00, z=3442.46], anw['Zombie'/10081, l='MpServer', x=-346.53, y=68.00, z=3448.37], aep['Area Effect Cloud'/10082, l='MpServer', x=-400.00, y=0.00, z=3440.00], aep['Area Effect Cloud'/10083, l='MpServer', x=-352.00, y=0.00, z=3424.00], aep['Area Effect Cloud'/10084, l='MpServer', x=-368.00, y=0.00, z=3408.00], aep['Area Effect Cloud'/10085, l='MpServer', x=-336.00, y=0.00, z=3440.00], anw['Zombie'/10086, l='MpServer', x=-328.50, y=69.00, z=3453.50], anw['Zombie'/10087, l='MpServer', x=-329.50, y=69.00, z=3448.50], aep['Area Effect Cloud'/10088, l='MpServer', x=-368.00, y=0.00, z=3472.00], aep['Area Effect Cloud'/10089, l='MpServer', x=-384.00, y=0.00, z=3472.00], amt['Creeper'/10090, l='MpServer', x=-376.50, y=52.00, z=3483.50], aep['Area Effect Cloud'/10091, l='MpServer', x=-400.00, y=0.00, z=3424.00], ame['Painting'/10254, l='MpServer', x=-303.00, y=64.50, z=3395.03], anw['Zombie'/10092, l='MpServer', x=-395.50, y=73.00, z=3428.58], aep['Area Effect Cloud'/10093, l='MpServer', x=-384.00, y=0.00, z=3408.00], aep['Area Effect Cloud'/10094, l='MpServer', x=-352.00, y=0.00, z=3408.00], aki['Squid'/10095, l='MpServer', x=-350.66, y=59.61, z=3409.90], aep['Area Effect Cloud'/10096, l='MpServer', x=-400.00, y=0.00, z=3456.00], aep['Area Effect Cloud'/10097, l='MpServer', x=-400.00, y=0.00, z=3408.00], aep['Area Effect Cloud'/10099, l='MpServer', x=-352.00, y=0.00, z=3472.00], aep['Area Effect Cloud'/10100, l='MpServer', x=-336.00, y=0.00, z=3424.00], aep['Area Effect Cloud'/10101, l='MpServer', x=-400.00, y=0.00, z=3472.00], aep['Area Effect Cloud'/10103, l='MpServer', x=-336.00, y=0.00, z=3408.00], aep['Area Effect Cloud'/10104, l='MpServer', x=-336.00, y=0.00, z=3456.00], aep['Area Effect Cloud'/10105, l='MpServer', x=-336.00, y=0.00, z=3472.00], aep['Area Effect Cloud'/10106, l='MpServer', x=-416.00, y=0.00, z=3440.00], aep['Area Effect Cloud'/10107, l='MpServer', x=-384.00, y=0.00, z=3488.00], aep['Area Effect Cloud'/10108, l='MpServer', x=-368.00, y=0.00, z=3392.00], ake['Salmon'/10109, l='MpServer', x=-364.90, y=62.49, z=3406.29], ake['Salmon'/10110, l='MpServer', x=-365.55, y=62.52, z=3405.53], aep['Area Effect Cloud'/10111, l='MpServer', x=-368.00, y=0.00, z=3488.00], aep['Area Effect Cloud'/10112, l='MpServer', x=-320.00, y=0.00, z=3440.00], aep['Area Effect Cloud'/10113, l='MpServer', x=-416.00, y=0.00, z=3456.00], aep['Area Effect Cloud'/10114, l='MpServer', x=-384.00, y=0.00, z=3392.00], aep['Area Effect Cloud'/10115, l='MpServer', x=-416.00, y=0.00, z=3424.00], aep['Area Effect Cloud'/10117, l='MpServer', x=-352.00, y=0.00, z=3392.00], aep['Area Effect Cloud'/10373, l='MpServer', x=-366.18, y=0.00, z=3447.31], aml['Falling Block'/10118, l='MpServer', x=-343.98, y=74.49, z=3396.93], aep['Area Effect Cloud'/10119, l='MpServer', x=-320.00, y=0.00, z=3456.00], aep['Area Effect Cloud'/10120, l='MpServer', x=-320.00, y=0.00, z=3424.00], aep['Area Effect Cloud'/10121, l='MpServer', x=-352.00, y=0.00, z=3488.00], ann['Skeleton'/10122, l='MpServer', x=-346.49, y=64.00, z=3495.75], amt['Creeper'/10123, l='MpServer', x=-343.99, y=64.00, z=3498.42], aep['Area Effect Cloud'/10124, l='MpServer', x=-336.00, y=0.00, z=3392.00], aki['Squid'/10125, l='MpServer', x=-320.36, y=58.69, z=3403.40], aki['Squid'/10126, l='MpServer', x=-320.56, y=57.26, z=3401.62], aep['Area Effect Cloud'/10128, l='MpServer', x=-416.00, y=0.00, z=3408.00], aep['Area Effect Cloud'/10131, l='MpServer', x=-400.00, y=0.00, z=3488.00], aep['Area Effect Cloud'/10133, l='MpServer', x=-336.00, y=0.00, z=3488.00], aep['Area Effect Cloud'/10134, l='MpServer', x=-400.00, y=0.00, z=3392.00], aep['Area Effect Cloud'/10135, l='MpServer', x=-416.00, y=0.00, z=3472.00], aep['Area Effect Cloud'/10136, l='MpServer', x=-320.00, y=0.00, z=3408.00], aep['Area Effect Cloud'/10148, l='MpServer', x=-384.00, y=0.00, z=3504.00], aep['Area Effect Cloud'/10149, l='MpServer', x=-416.00, y=0.00, z=3392.00], aep['Area Effect Cloud'/10151, l='MpServer', x=-416.00, y=0.00, z=3488.00], ann['Skeleton'/10152, l='MpServer', x=-415.50, y=52.00, z=3498.15], ann['Skeleton'/10153, l='MpServer', x=-405.50, y=51.00, z=3501.73], aep['Area Effect Cloud'/10154, l='MpServer', x=-368.00, y=0.00, z=3504.00], aep['Area Effect Cloud'/10156, l='MpServer', x=-320.00, y=0.00, z=3472.00], ann['Skeleton'/10157, l='MpServer', x=-311.50, y=34.00, z=3484.50], aep['Area Effect Cloud'/10164, l='MpServer', x=-304.00, y=0.00, z=3440.00], aep['Area Effect Cloud'/10165, l='MpServer', x=-304.00, y=0.00, z=3424.00], aep['Area Effect Cloud'/10166, l='MpServer', x=-400.00, y=0.00, z=3504.00], anw['Zombie'/10167, l='MpServer', x=-398.50, y=43.00, z=3504.50], aep['Area Effect Cloud'/10168, l='MpServer', x=-320.00, y=0.00, z=3488.00], aep['Area Effect Cloud'/10169, l='MpServer', x=-304.00, y=0.00, z=3456.00], aep['Area Effect Cloud'/10170, l='MpServer', x=-352.00, y=0.00, z=3504.00], amt['Creeper'/10171, l='MpServer', x=-346.48, y=64.00, z=3508.23], amt['Creeper'/10172, l='MpServer', x=-346.18, y=64.00, z=3507.41], aep['Area Effect Cloud'/10173, l='MpServer', x=-320.00, y=0.00, z=3392.00], alz['Armor Stand'/10174, l='MpServer', x=-305.13, y=62.00, z=3399.50], alz['Armor Stand'/10175, l='MpServer', x=-304.88, y=62.00, z=3396.50], alz['Armor Stand'/10176, l='MpServer', x=-305.50, y=62.00, z=3398.50], alz['Armor Stand'/10177, l='MpServer', x=-304.50, y=62.00, z=3398.50], alz['Armor Stand'/10178, l='MpServer', x=-304.50, y=62.00, z=3397.50], alz['Armor Stand'/10179, l='MpServer', x=-305.50, y=62.00, z=3397.50], amb['Item Frame'/10180, l='MpServer', x=-305.97, y=63.50, z=3401.50], aki['Squid'/10181, l='MpServer', x=-314.29, y=58.43, z=3403.40], ake['Salmon'/10182, l='MpServer', x=-319.50, y=60.13, z=3403.88], ake['Salmon'/10183, l='MpServer', x=-319.44, y=58.89, z=3405.34], ame['Painting'/10184, l='MpServer', x=-306.97, y=65.00, z=3401.50], ame['Painting'/10185, l='MpServer', x=-306.97, y=65.00, z=3397.00], ame['Painting'/10186, l='MpServer', x=-306.97, y=65.00, z=3406.00], aep['Area Effect Cloud'/10191, l='MpServer', x=-416.00, y=0.00, z=3504.00], ann['Skeleton'/10197, l='MpServer', x=-401.50, y=43.00, z=3508.50], amt['Creeper'/10202, l='MpServer', x=-421.50, y=56.00, z=3500.81], anw['Zombie'/10203, l='MpServer', x=-420.50, y=56.00, z=3503.50], aep['Area Effect Cloud'/10205, l='MpServer', x=-304.00, y=0.00, z=3472.00], aep['Area Effect Cloud'/10207, l='MpServer', x=-336.00, y=0.00, z=3504.00], aep['Area Effect Cloud'/10210, l='MpServer', x=-304.00, y=0.00, z=3408.00], aep['Area Effect Cloud'/10223, l='MpServer', x=-320.00, y=0.00, z=3504.00], ann['Skeleton'/10228, l='MpServer', x=-312.50, y=18.00, z=3425.50], amt['Creeper'/10229, l='MpServer', x=-317.50, y=18.00, z=3424.50], amt['Creeper'/10230, l='MpServer', x=-314.50, y=18.00, z=3423.50], anw['Zombie'/10232, l='MpServer', x=-314.50, y=18.00, z=3429.50]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(WorldClient.java:576)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 424640552 bytes (404 MB) / 738197504 bytes (704 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-OptiFine_HD_U_E7
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 1060/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Extreme
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz`

**Comment by cakoyo** [comment]
Is there any way to reproduce this crash?

**Comment by WhyDoWeWonder** [comment]
Fixed, it had very little to actually do with Akarin.
