### ISSUE TITLE
Ping bug 1.12.2

### ISSUE THREAD

**Issue by Clercq** [Akarin-project/Akarin#92]
In TAB Ping too high(1000-5000ms), but really ping lower than 100

**Comment by cakoyo** [comment]
1.12.2 branch is inactive for a while, but I don't remember there is such a bug. I'm not meant to fix it since it's not that 'critical' and the debug is very hard since there is no error log. (actually, I've removed my 1.12.2 workspace)

**Comment by cakoyo** [comment]
I highly recommend you update to Akarin 1.13.2, the latest version is more stable. Feel free to reply if you need any further assistance.

**Comment by Clercq** [comment]
today 1.13.2 (not Akarin, minecraft client) is so laggy, many players(arround 40% of all my server users) reports me that they has a low FPS

**Comment by WhyDoWeWonder** [comment]
Try using Protocol Support or ViaVersion so 1.12.2 be clients can join your server. If this is not an option for you then give us as much information as possible. This includes a list of plugins, server logs, Java version and if you experience this bug using Paper, Spigot, and/or Craftbukkit. As an alternative option you could use a 3rd party system to detect ping and modify the tab display to show the exact ping value in tab.If you require any assistance with the options listed above please feel free to tell us.
