### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by Clercq** [Akarin-project/Akarin#93]
sry, but really need 1.12.2 and latest paper, how to compile it?
ur core has good optimization (160 players, 20TPS in Akarin vs 100 players, 12TPS in Paper)
Can u give guide for compile it for 1.12.2(latest paper), because ./scripts/inst.sh --setup --fast doesn't work
------------------
I unlike 1.13 because users say that its very laggy
------------------
It gets 1.13.2 version, but i need 1.12.2:C

**Comment by CBM1014** [comment]
We had found that inst.sh for akarin 1.12 cannot work properly. It may NOT be fixed in a short time. You may try to find 1.12 artifacts at our Circle CI page. You can find the link of it in README.md.
This issue will remain open until the issue solved by us.

**Comment by Clercq** [comment]
i can pay 10$ for build on latest paper(1.12.2)

**Comment by Clercq** [comment]
@CBM1014

**Comment by cakoyo** [comment]
You can download 1.12.2 version from our circleci archive
https://circleci.com/gh/Akarin-project/Akarin/tree/ver%2F1.12.2
