### ISSUE TITLE
suggestion:How could donate on patron

### ISSUE THREAD

**Issue by roughanddai** [Akarin-project/Akarin#95]
i even cannot open the website in Jiangsu,China
maybe need alipay to donate 
😂

**Comment by WhyDoWeWonder** [comment]
The Akarin Project's Patreon page is located [here](https://www.patreon.com/akarinproject) simply go to the website and click on sign up in the top right hand corner or login if you already have an account. Next, after creating your account or logging in go to https://www.patreon.com/settings/payment to setup a payment method. Finally go back to https://www.patreon.com/akarinproject and then select how much you wish to donate. Finally, confirm your payment.

There you're all done!
