### ISSUE TITLE
Question: Can you update to 1.14.3?

### ISSUE THREAD

**Issue by flyingcatt3** [Akarin-project/Akarin#96]
I'm sorry to trouble you. I really need 1.14.3 support.
甚麼時候更新到最新版(´・ω・`)

**Comment by arturek1666** [comment]
Please join discord if you want more info about update however I can say that 1.14.3 is in really not stable stage and they wait on more stabile minecraft version like 1.14.5 our higher, you just have to wait for update ;)

**Comment by josephworks** [comment]
@arturek1666 1.14.5 isn't even a thing, and @flyingcatt3 do you still need 1.14.3?

**Comment by josephworks** [comment]
@flyingcatt3 if you still need 1.14.3, use paper for now until you can upgrade to Akarin 1.14.4. Thanks!
