### ISSUE TITLE
akarin dead or just being busy?

### ISSUE THREAD

**Issue by TheCompieter** [Akarin-project/Akarin#98]
i have been wondering what happend to akarin just a bit worried more not.

**Comment by xBraken** [comment]
it's dead

**Comment by TechDroid2002** [comment]
it isnt dead if you look at discord chat there waiting on 1.14 to be stable

**Comment by TheCompieter** [comment]
ty i will look but 1.14.4 is the latest bugfix from mojang until 1.15, or are they waiting for paperspigot/bukkit/craftbukkit/spigot to be stable?

**Comment by cakoyo** [comment]
I hope it does not go to die, however, Mojang just brings the game worse and worse after 1.13 and it is hard to handle stuff like multi-threading, at least, for me. I can not choose, it beyond me now.

**Comment by CamJW101** [comment]
@TheCompieter 1.14.4 is the final patch before 1.15 per https://www.minecraft.net/en-us/article/minecraft-java-1-14-4-released

**Comment by TheCoolOne123** [comment]
1.15 has been released a few days ago. I've heard 1.15 is more stable rn

**Comment by josephworks** [comment]
It looks as if Akarin is waiting for Paper to be more stable. In order for that to happen 1.14.4 has to be stable, craftbukkit has to be stable, spigot has to be stable, paper has to be stable. Now that Paper is working on 1.15, we can assume that paper 1.14.4 is stable and we can begin development. It could also be that some developers are busy for the time being.

**Comment by LegacyGamerHD** [comment]
@josephworks why did you close it

**Comment by josephworks** [comment]
Cause I answered and resolved it. Do you have any questions? 
Any which way, it isn't dead as I am working on it right now...

**Comment by liach** [comment]
There are projects like https://github.com/Akarin-project/StarLink that has other optimizations.
